### ISSUE TITLE
Shortcut.exe code?

### ISSUE THREAD

**Issue by fourpixels** [j201/windows-shortcuts#2]
Hi there,
First - thanks for the great library - it seems to work pretty well. I just wanted to ask if there is a way to see the code of Shortcut.exe or somehow know everything there is alright? I'm kind of worried to pack exe file that I don't truly know.. I couldn't find anything online..

Thanks in advance!

**Comment by j201** [comment]
I don't think the source code is available. I haven't had any issues in using it, but I can't make any guarantees. You might be able to get the source from the [original developer](http://www.optimumx.com/contact.html). The licence also doesn't seem to prohibit decompilation, although it might be hard to get useful information from that.
