### ISSUE TITLE
Make it possible to install on non Windows OS

### ISSUE THREAD

**Issue by soichih** [j201/windows-shortcuts#7]
Hello. 

I am developing a multi-platform app using electron, and I am trying to use windows-shortcuts to be used _only_ when user is running my app on Windows. Is there anyway to make this module behave similar to node-winreg? It allows me to install it on non-Windows OS - although invoking it on non-Windows will results in error.

**Comment by sujkh85** [comment]
+1

**Comment by j201** [comment]
b00cc1f98f3a69c7a50fdb42ab5e91f383c23e0f
